[package]
name = "file-renamer"
version = "0.1.0"
edition = "2024"

[build-dependencies.chrono]
version = "0.4.40"

[dependencies.uuid]
version = "1.15.1"
features = ["v4"]

[dependencies.clap]
version = "4.5.30"
